### ISSUE TITLE
Bugs & Improvements

### ISSUE THREAD

**Issue by ghost** [cfredric/NumberTheory#1]
I took a look into the code of some functions and found some bugs and ideas for improvements.

**General:**
- the usage of `quot` instead of `div` and `rem` instead of `mod` is said to be more efficient
- when it is necessary to calculate both the quotient and reminder i recommend to use `quotRem` which calculates both at the same time

**toText:**
- `toText 123` returns `"{"`
- `toText 12345` returns `"09"`
- negative number results in infinite loop
- the error appears because of `div 256` instead of `div 10` and a missing padding to convert a number between 0 and 9 into chars from '0' to '9'; '0' -> 48
- this function is not necessary because of `show` (Show Instance of Int and Integer)
- Anyway, this code works:
```haskell
toText :: Integral a => a -> String
toText n = case (compare n 0) of
  LT -> "-" ++ (go $ abs n) 
  EQ -> "0"
  GT -> go n
  where go 0 = ""
        go n = let (q,r) = quotRem n 10 
               in (go q) ++ [Char.chr $ fromIntegral $ 48 + r]
```

**fromText:**
- `fromText "123"` returns `3224115`
- same mistake as in `toText`
- this function is not necessary because of `read` (Read instance of Int and Integer)
- Anyway, this code works:
```haskell
fromText = foldl' (\n c -> 10 * n + fromIntegral (Char.ord c) - 48) 0
```

**collapseMultiplicities:**
- the implementation seems to be not that efficient
- because the factors from `findFactors` are in ascending order they can simply be reduced into pairs; not necessary to create Map and afterwards convert it back into List
```haskell
combine []       = []
combine (x : xs) = let (a, b) = span (== x) xs
                   in (x, 1 + length a) : combine b
```
- alternative: use `Map.fromAscListWith` or `Map. fromDistinctAscList` because of the known preconditions 

**totient:**
- The implementation seems to be efficient for some numbers and less efficient for others, interesting:
```haskell
> totient (10^10)
4000000000
(0.23 secs, 92,026,944 bytes)
```
- I did an own implementation based on the third formula from [Wikipedia#Other_formulae](https://en.wikipedia.org/wiki/Euler%27s_totient_function#Other_formulae) which checks this property for the first few prime numbers; this reduces the number as long as it is greater than some limit; if the number is smaller that the limit simply count coprime numbers; its not perfect either (slow on other numbers ;) )
```haskell
> phi (10^10)
4000000000
(0.04 secs, 4,420,112 bytes)
```

**isPrime:**
- inefficient to generate all primes
- if you first drop all numbers less than the number, you don't need to use `takeWhile` nor `elem`; simply use `n == head` because if `n` is prime is must be the first number to appear

**nmerge:**
- l.346: It is not important to check if some lists are empty, just use the filter all the time because `any` is evaluated every time anyways

**GaussInt:**
- `1 :+ 0` is shown as `1-0i`
- `0 :+ 0` is shown as `0-0i`
- missing check for equality with 0
- this datatype is not necessary because complex numbers are part of `Data.Complex` which can be imported by default

**fibonacci:**
- your implementation is very common, but very slow (because of massive recursion using `zipWith` (+)):
```haskell
> length $ take 30 fibonacci 
30
(1.74 secs, 672,827,624 bytes)
```
- a cusotm implementation is way more efficient:
```haskell
fibonacci :: Num a => [a]
fibonacci = go 0 1
  where go a b = a : go b (a + b)
```
and
```haskell
> length $ take 30 fibonacci
30
(0.01 secs, 91,000 bytes)
```
**UPDATE:**
- alternative and even better implementation: `fibonacci = 0 : scanl (+) 1 fibonacci`

**permute:**
- tests for negative numbers?
- test for `k > n`?
- the factorial up to `(n-k)` is within the factorial up to `n` which means that you make a lot of calculation twice, which is not even used because of the division
- a better implementation would be to do not calc `factorial (n-k)` at all and just calc `product [(n - k + 1)..n]`, no division needed
- Before:
```Haskell
(0.02 secs, 2,265,048 bytes)
```
- After:
```Haskell
(0.02 secs, 1,591,688 bytes)
```

Hope i could help.

**Comment by cfredric** [comment]
Hi ghost,

Thanks for looking into these and providing such thorough feedback! Unfortunately I'm no longer maintaining this library, and I don't plan on doing any more active development on it. Please feel free to fork it, or to use the more mature [arithmoi](https://github.com/cartazio/arithmoi) library instead.
